### ISSUE TITLE
New feature proposal: support multiple templates folder (other nodejs impls or either other platforms)

### ISSUE THREAD

**Issue by jantoniucci** [asyncapi/node-codegen#6]
I am thinking about implementing another asyncapi codegen to support another platforms than node. Basically, a fork of node-codegen with specific templates. But I realized that all I need to change is related to handlebars templates. 

I also note that other codegens like https://github.com/swagger-api/swagger-codegen brings an argument to define a templates folder like `[(-t <template directory> | --template-dir <template directory>)]`.

If you see this approach is valid for your codegen, I can contribute a PR implementing this new argument.

Thanks!

Javier A.

**Comment by fmvilas** [comment]
Hey @jantoniucci. I'm glad you propose that because it was on the roadmap. Recently @richardklose implemented what you say in my other package for OpenAPI (https://github.com/fmvilas/swagger-node-codegen). I was thinking on implementing it in the same way. This, as you said, will allow us to have different platforms, languages, frameworks, etc.

I'll appreciate a PR since I'm very busy working on the new AsyncAPI features. I'll help with anything you need, of course. You can [join the Slack](https://async-apis-slack.herokuapp.com/) channel if you want.

Cheers!
